# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ad5ffe87dbebff1f6817bb8f9371e842"
name = "BundleApp-V5"
handle = "bundleapp-v5"
application_url = "https://flood-developmental-patch-institute.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "bundle-app-v6.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,read_locales,read_orders,read_publications,read_themes,write_cart_transforms,write_discounts,write_products"

[auth]
redirect_urls = [
  "https://flood-developmental-patch-institute.trycloudflare.com/auth/callback",
  "https://flood-developmental-patch-institute.trycloudflare.com/auth/shopify/callback",
  "https://flood-developmental-patch-institute.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [
  "app/uninstalled",
  "orders/create",
  "products/delete",
  "products/update"
]
  uri = "https://simplebundle.onrender.com/webhooks"

[pos]
embedded = false
